- name: start db container
  docker_container:
    name: database
    image: vitush19/tp-devops:docker-tp2-database
    state: started
    restart: yes
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD=pwd
      POSTGRES_USER=usr
      POSTGRES_DB=db
# tasks file for roles/database