language: java

jobs:
  include:
    - stage: develop
      name: Test 1
      script: bash scripts/build.sh
    - stage: prod
      name: Test 2
      script: bash scripts/docker.sh 

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "vitush19"
    token: "$SONARCLOUD_TOKEN"