language: java
script:
  - cd ./simple-api
  - mvn clean verify

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t $DOCKER_USERNAME/tp-devops .
  
  - docker push $DOCKER_USERNAME/tp-devops

  branches: 
    only:
      - develop

  cache:
    directories:
      - $HOME/.m2
    services:
      - docker
