language: java

script:
  - cd ./simple-api
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Vitush19_Docker

  # Connexion à Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build
  - docker build -t $DOCKER_USERNAME/tp-devops .
  # Publication des images
  - docker push $DOCKER_USERNAME/tp-devops

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker

notifications:
  email:false

addons:
  sonarcloud:
    organization: "Vitush19"
    token: "$SONARCLOUD_TOKEN"